import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
import {EditorController} from '../server/controller.mjs';
import {blankProject} from '../server/project.mjs';
const options={timing:{move:30,drag:150,type:1,pause:30}},base='http://127.0.0.1:8601';
let c=await new EditorController(base,options).open();
try{
  const buffer=await fs.readFile('PEN動作確認.sb3');await c.load(buffer);await c.load(await blankProject(buffer));await c.selectTarget('ペン');
  await c.execute({type:'variable.create',sourceId:'source-var',name:'保存する変数',scope:'global',value:7});
  const mutation={proccode:'テスト %s %b',argumentnames:'["数","条件"]',argumentids:'["source-number","source-bool"]',argumentdefaults:'["",false]',warp:'true'};
  await c.execute({type:'procedure.create',sourceId:'source-def',prototypeId:'source-proto',mutation,x:200,y:200});
  await c.execute({type:'block.add',sourceId:'source-call',opcode:'procedures_call',mutation,place:{after:'source-def'}});
  await c.execute({type:'broadcast.create',sourceId:'source-message',name:'再開メッセージ'});
  await c.execute({type:'block.add',sourceId:'source-say',opcode:'looks_say',place:{x:500,y:500}});
  await c.execute({type:'block.add',sourceId:'source-reporter',opcode:'data_variable',fields:{VARIABLE:['保存する変数','source-var']},place:{parent:'source-say',input:'MESSAGE'}});
  await c.execute({type:'view.configure',minScale:1});
  const before=await c.state();
  assert.equal(before.blocks.find(b=>b.sourceId==='source-call').inputs.find(i=>i.sourceName==='source-number').sourceName,'source-number');
  await c.category('variables');await c.click(c.page.locator('.blocklyFlyoutButton').filter({hasText:'変数を作る'}));
  assert.equal((await c.state()).modal.type,'prompt');
  await c.click(c.page.getByRole('button',{name:'キャンセル',exact:true}));assert.equal((await c.state()).modal,null);
  await c.category('myBlocks');await c.click(c.page.locator('.blocklyFlyoutButton').filter({hasText:'ブロックを作る'}));
  assert.equal((await c.state()).modal.type,'procedure');
  await c.click(c.page.getByRole('button',{name:'キャンセル',exact:true}));
  const state=await c.checkpoint(),snapshot=await c.save();assert.equal(state.minScale,1);
  for(const key of ['aliases','procedures','variableRefs','broadcastNames','callArgs'])assert.ok(state.maps[key].length,key);
  await c.close();c=await new EditorController(base,options).open();await c.restoreCheckpoint(snapshot,state);
  assert.equal(c.target,state.view.target);assert.equal(c.minScale,1);
  for(const key of Object.keys(state.maps).filter(k=>k!=='aliases'))assert.deepEqual([...c[key]],state.maps[key],key);
  const reporterIds=new Set(state.reporters.map(b=>b.id));
  for(const [key,id] of state.maps.aliases)if(!reporterIds.has(id))assert.equal(c.aliases.get(key),id,key);
  const observed=await c.state();
  assert.ok(observed.blocks.some(b=>b.sourceId==='source-def'));
  assert.equal(observed.blocks.find(b=>b.sourceId==='source-call').inputs.find(i=>i.sourceName==='source-number').sourceName,'source-number');
  assert.ok(observed.blocks.some(b=>b.sourceId==='source-reporter'),'compact variable alias after restore');
  const restored=await c.checkpoint();assert.equal(restored.view.scale,state.view.scale);assert.ok(Math.abs(restored.view.x-state.view.x)<1&&Math.abs(restored.view.y-state.view.y)<1);
  await c.execute({type:'workspace.focus',block:'source-reporter'});
  assert.ok(state.view.extensions.includes('pen'));await c.category('pen');
  await c.execute({type:'block.input',block:'source-call',input:'source-number',value:'12345'});
  await c.ensureVisible(c.resolve('source-call'),c.mappedInput('source-call','source-number'));
  const field=await c.page.evaluate(({id,input})=>studio.fieldInfo(id,input),{id:c.resolve('source-call'),input:c.mappedInput('source-call','source-number')});
  assert.equal(field.value,'12345');await c.clickBox(field.box);assert.equal((await c.state()).fieldEditorOpen,true);
  await c.page.keyboard.press('Escape');assert.equal((await c.state()).fieldEditorOpen,false);
  await c.execute({type:'block.add',sourceId:'source-argument',opcode:'argument_reporter_boolean',fields:{VALUE:['条件',null]},place:{parent:'source-call',input:'source-bool'}});
  await c.verifyConnection(c.resolve('source-argument'),{parent:'source-call',input:'source-bool'});
  await c.execute({type:'block.add',sourceId:'source-receive',opcode:'event_whenbroadcastreceived',place:{x:400,y:500}});
  await c.execute({type:'block.field',block:'source-receive',field:'BROADCAST_OPTION',referenceId:'source-message'});
  assert.deepEqual(c.errors,[]);await c.page.screenshot({path:'test-results/checkpoint-state.png'});
  console.log('PASS: ID maps including compact reporters, view/target/zoom, source input names, live dialogs and fields, restored operations');
}finally{await c.close();}
